#!/bin/bash
defUsers="root bin daemon adm lp sync shutdown halt mail news uucp operator games
gopher ftp nobody nscd vcsa rpc mailnull smmsp pcap ntp dbus avahi sshd rpcuser
nfsnobody haldaemon avahi-autoipd distcache apache oprofile webalizer dovecot squid
named xfs gdm sabayon"
/bin/cat /etc/passwd | while:
do
x=`line`
if [ "$x" = "" ]
then
break
fi
userid=`echo "$x" | cut -f1 -d':'`
found=0
for n in $defUsers
do
if [ $userid = "$n" ]
then
found=1
break
fi
done
if [ $found -eq 1 ]
then
continue
fi
groupid=`echo "$x" | /bin/cut -f4 -d':'`
/bin/cat /etc/group | while :
do
x=`line`
if [ "$x" = "" ]
then
echo "Groupid $groupid does not exist in /etc/group, but is used by $userid"
break
fi
y=`echo $x | cut -f3 -d":"`
if [ $y -eq $groupid ]
then
break
fi
done
done
