#!/bin/bash
echo "The Output for the Audit of Control 9.14 - Check User Home Directory Ownership
is"
defUsers="root bin daemon adm lp sync shutdown halt mail news uucp operator games
gopher ftp nobody nscd vcsa rpc mailnull smmsp pcap ntp dbus avahi sshd rpcuser
nfsnobody haldaemon avahi-autoipd distcache apache oprofile webalizer dovecot squid
named xfs gdm sabayon"
/usr/bin/cat /etc/passwd | \
awk -F: '{ print $1 " " $6 }' |\
while read user dir; do
found=0
for n in $defUsers
do
if [ "$user" = "$n" ]
then
found=1
break
fi
done
if [ $found -eq "0" ]
then
if [ -d ${dir} ]
then
owner=`ls -ld $dir | sed -e 's/ */ /g' | cut -f3 -d" "`
if [ "$owner" != "$user" ]
then
echo "Home directory for $user owned by $owner"
fi
fi
fi
done
